### ISSUE TITLE
Maybe quickly mention some of the research you've done

### ISSUE THREAD

**Issue by phw** [skelly37/GSoC-2022#1]
Hi @skelly37,

for me this proposed summary looks very good. Actually quite an amount of changes done to Picard, this was great.

A minor improvement for

https://github.com/skelly37/GSoC-2022/blob/5135a728ff0be0c9832b0a58e87439537e8530d7/README.md?plain=1#L45

would be to make a quick mention of some of the technologies you researched there. Nothing in deep, just mention the things.

But I'd be happy to have this submitted as is.

**Comment by skelly37** [comment]
Thanks for the feedback, done :)
